<?php

namespace Tests\Feature;

use App\Actions\SyncConnection;
use App\Models\Connection;
use App\Models\Institution;
use App\Models\RiskProfile;
use App\Models\User;
use App\Services\Analytics\PortfolioAnalyzer;
use Database\Seeders\NewsSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Volt\Volt;
use Tests\TestCase;

class StretchFeaturesTest extends TestCase
{
    use RefreshDatabase;

    private function analyzedUser(): User
    {
        $user = User::factory()->create();
        RiskProfile::factory()->balanced()->create(['user_id' => $user->id]);

        $institution = Institution::factory()->create(['slug' => 'derayah']);
        $connection = Connection::factory()->pending()->create([
            'user_id' => $user->id,
            'institution_id' => $institution->id,
        ]);

        app(SyncConnection::class)->handle($connection);
        app(PortfolioAnalyzer::class)->analyze($user->fresh());

        return $user;
    }

    public function test_the_news_feed_shows_items_matching_holdings_with_a_relevance_line(): void
    {
        (new NewsSeeder)->run();
        $this->actingAs($this->analyzedUser());

        Volt::test('dashboard.news-feed')
            ->assertSee('Apple earnings preview', escape: false)
            ->assertSee(__('You hold'))
            // The Aramco story is tagged 2222.SR / Energy — neither is held.
            ->assertDontSee('Aramco maintains dividend');
    }

    public function test_the_news_feed_is_empty_without_relevant_holdings(): void
    {
        (new NewsSeeder)->run();
        $this->actingAs(User::factory()->create());

        Volt::test('dashboard.news-feed')
            ->assertSee(__('No news relevant to your holdings right now.'));
    }

    public function test_a_concentrated_portfolio_triggers_the_concentration_alert(): void
    {
        $this->actingAs($this->analyzedUser());

        // The Derayah-only portfolio holds ~49% AAPL — above the 30% threshold.
        Volt::test('dashboard.alerts')
            ->assertSee('Concentration alert')
            ->assertSee('Apple');
    }

    public function test_users_without_a_snapshot_get_no_alerts(): void
    {
        $this->actingAs(User::factory()->create());

        Volt::test('dashboard.alerts')->assertDontSee('alert:');
    }

    public function test_the_report_page_renders_the_full_analysis(): void
    {
        $this->actingAs($this->analyzedUser());

        $this->get('/report')
            ->assertOk()
            ->assertSee(__('Portfolio Report'))
            ->assertSee(__('Key Metrics'))
            ->assertSee(__('Sharpe Ratio'))
            ->assertSee('/100')
            ->assertSee(__('This report is educational analysis generated by Mahafeth and is not licensed financial advice.'));
    }

    public function test_the_report_page_redirects_guests(): void
    {
        $this->get('/report')->assertRedirect('/login');
    }
}
